title: Federico Sossai
logo: /assets/img/profilepic.jpg
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
site.show_downloads: false
site.github.is_project_page: false
